// Autogenerated pure vector geometric dissection models for Sri Yantra
// Perfectly symmetric, topologically verified, canonical 9-Avarana vectors
// Scale: 1000x1000 viewBox, center (500, 500)

export interface AvaranaDissectionData {
  index: number;
  nameSanskrit: string;
  nameEnglish: string;
  chakraTitle: string;
  geometryType: string;
  count: number;
  svgElement: string;
}

export const SRI_YANTRA_VECTOR_DISSECTIONS: Record<number, AvaranaDissectionData> = {
  1: {
    index: 1,
    nameSanskrit: "त्रैलोक्यमोहन चक्र (भूपुर प्राकार / 3 रेखाएं व 4 द्वार)",
    nameEnglish: "Trailokyamohana Chakra (Bhupura Earth Rampart & 4 Gates)",
    chakraTitle: "भूपुर प्राकार (चतुरस्र)",
    geometryType: "3 Stepped Concentric Squares with 4 Cardinal Portals",
    count: 4,
    svgElement: `<g id="dissection_bhupura">
  <path d="M 60 60 L 420.8 60 L 420.8 24.8 L 579.2 24.8 L 579.2 60 L 940 60 L 940 420.8 L 975.2 420.8 L 975.2 579.2 L 940 579.2 L 940 940 L 579.2 940 L 579.2 975.2 L 420.8 975.2 L 420.8 940 L 60 940 L 60 579.2 L 24.8 579.2 L 24.8 420.8 L 60 420.8 Z M 79.8 79.8 L 440.6 79.8 L 440.6 44.6 L 559.4 44.6 L 559.4 79.8 L 920.2 79.8 L 920.2 440.6 L 955.4 440.6 L 955.4 559.4 L 920.2 559.4 L 920.2 920.2 L 559.4 920.2 L 559.4 955.4 L 440.6 955.4 L 440.6 920.2 L 79.8 920.2 L 79.8 559.4 L 44.6 559.4 L 44.6 440.6 L 79.8 440.6 Z M 99.6 99.6 L 460.4 99.6 L 460.4 64.4 L 539.6 64.4 L 539.6 99.6 L 900.4 99.6 L 900.4 460.4 L 935.6 460.4 L 935.6 539.6 L 900.4 539.6 L 900.4 900.4 L 539.6 900.4 L 539.6 935.6 L 460.4 935.6 L 460.4 900.4 L 99.6 900.4 L 99.6 539.6 L 64.4 539.6 L 64.4 460.4 L 99.6 460.4 Z" fill="none" stroke="#FFD700" stroke-width="2.6" stroke-linejoin="round" />
</g>`
  },
  2: {
    index: 2,
    nameSanskrit: "सर्वाशापरिपूरक चक्र (षोडशदल पद्म / 16 कमल पंखुड़ियाँ)",
    nameEnglish: "Sarvashaparipuraka Chakra (16-Petal Lotus)",
    chakraTitle: "षोडशदल पद्म चक्र",
    geometryType: "16 Sacred Lotus Petals with Outer Ring",
    count: 16,
    svgElement: `<g id="dissection_shodashadala">
  <circle cx="500" cy="500" r="392" fill="none" stroke="#FFD700" stroke-width="1.8" stroke-dasharray="3 3" opacity="0.6" />
  <path d="M 436.4 180.26 Q 459.01 128.74, 500 108 Q 540.99 128.74, 563.6 180.26 M 563.6 180.26 Q 604.21 141.31, 650.01 137.84 Q 679.94 172.68, 681.12 228.94 M 681.12 228.94 Q 733.54 208.49, 777.19 222.81 Q 791.51 266.46, 771.06 318.88 M 771.06 318.88 Q 827.32 320.06, 862.16 349.99 Q 858.69 395.79, 819.74 436.4 M 819.74 436.4 Q 871.26 459.01, 892 500 Q 871.26 540.99, 819.74 563.6 M 819.74 563.6 Q 858.69 604.21, 862.16 650.01 Q 827.32 679.94, 771.06 681.12 M 771.06 681.12 Q 791.51 733.54, 777.19 777.19 Q 733.54 791.51, 681.12 771.06 M 681.12 771.06 Q 679.94 827.32, 650.01 862.16 Q 604.21 858.69, 563.6 819.74 M 563.6 819.74 Q 540.99 871.26, 500 892 Q 459.01 871.26, 436.4 819.74 M 436.4 819.74 Q 395.79 858.69, 349.99 862.16 Q 320.06 827.32, 318.88 771.06 M 318.88 771.06 Q 266.46 791.51, 222.81 777.19 Q 208.49 733.54, 228.94 681.12 M 228.94 681.12 Q 172.68 679.94, 137.84 650.01 Q 141.31 604.21, 180.26 563.6 M 180.26 563.6 Q 128.74 540.99, 108 500 Q 128.74 459.01, 180.26 436.4 M 180.26 436.4 Q 141.31 395.79, 137.84 349.99 Q 172.68 320.06, 228.94 318.88 M 228.94 318.88 Q 208.49 266.46, 222.81 222.81 Q 266.46 208.49, 318.88 228.94 M 318.88 228.94 Q 320.06 172.68, 349.99 137.84 Q 395.79 141.31, 436.4 180.26 " fill="rgba(212,175,55,0.18)" stroke="#FFD700" stroke-width="2.2" stroke-linejoin="round" />
  <circle cx="500" cy="500" r="326" fill="none" stroke="#FFD700" stroke-width="1.8" />
</g>`
  },
  3: {
    index: 3,
    nameSanskrit: "सर्वसंक्षोभण चक्र (अष्टदल पद्म / 8 कमल पंखुड़ियाँ)",
    nameEnglish: "Sarvasankshobhana Chakra (8-Petal Lotus)",
    chakraTitle: "अष्टदल पद्म चक्र",
    geometryType: "8 Sacred Lotus Petals with Concentric Boundaries",
    count: 8,
    svgElement: `<g id="dissection_ashtadala">
  <circle cx="500" cy="500" r="320" fill="none" stroke="#FFD700" stroke-width="1.8" />
  <path d="M 402.03 263.49 Q 434.1 205.2, 500 180 Q 565.9 205.2, 597.97 263.49 M 597.97 263.49 Q 661.86 244.95, 726.27 273.73 Q 755.05 338.14, 736.51 402.03 M 736.51 402.03 Q 794.8 434.1, 820 500 Q 794.8 565.9, 736.51 597.97 M 736.51 597.97 Q 755.05 661.86, 726.27 726.27 Q 661.86 755.05, 597.97 736.51 M 597.97 736.51 Q 565.9 794.8, 500 820 Q 434.1 794.8, 402.03 736.51 M 402.03 736.51 Q 338.14 755.05, 273.73 726.27 Q 244.95 661.86, 263.49 597.97 M 263.49 597.97 Q 205.2 565.9, 180 500 Q 205.2 434.1, 263.49 402.03 M 263.49 402.03 Q 244.95 338.14, 273.73 273.73 Q 338.14 244.95, 402.03 263.49 " fill="rgba(217,119,6,0.22)" stroke="#FFD700" stroke-width="2.4" stroke-linejoin="round" />
  <circle cx="500" cy="500" r="256" fill="none" stroke="#FFD700" stroke-width="1.8" />
</g>`
  },
  4: {
    index: 4,
    nameSanskrit: "सर्वसौभाग्यदायक चक्र (चतुर्दशार / 14 त्रिकोण)",
    nameEnglish: "Sarvasaubhagyadayaka Chakra (14 Triangles)",
    chakraTitle: "चतुर्दशार चक्र",
    geometryType: "14 Outer Perimeter Triangles",
    count: 14,
    svgElement: `<g id="dissection_chaturdasharam" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round">
  <circle cx="500" cy="500" r="250" fill="none" stroke="#FFD700" stroke-width="1.5" opacity="0.6" stroke-dasharray="4 2" />
  <polygon id="chaturdasharam_0" points="500,250 541.17,319.64 458.83,319.64" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_1" points="608.47,274.76 615.35,355.36 541.17,319.64" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_2" points="695.46,344.13 666.68,419.73 615.35,355.36" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_3" points="743.73,444.37 685,500 666.68,419.73" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_4" points="743.73,555.63 666.68,580.27 685,500" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_5" points="695.46,655.87 615.35,644.64 666.68,580.27" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_6" points="608.47,725.24 541.17,680.36 615.35,644.64" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_7" points="500,750 458.83,680.36 541.17,680.36" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_8" points="391.53,725.24 384.65,644.64 458.83,680.36" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_9" points="304.54,655.87 333.32,580.27 384.65,644.64" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_10" points="256.27,555.63 315,500 333.32,580.27" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_11" points="256.27,444.37 333.32,419.73 315,500" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_12" points="304.54,344.13 384.65,355.36 333.32,419.73" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_13" points="391.53,274.76 458.83,319.64 384.65,355.36" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  5: {
    index: 5,
    nameSanskrit: "सर्वार्थसाधक चक्र (बहिर्दशार / 10 बाहरी त्रिकोण)",
    nameEnglish: "Sarvarthasadhaka Chakra (10 Outer Triangles)",
    chakraTitle: "बहिर्दशार चक्र",
    geometryType: "10 Outer Circuit Triangles",
    count: 10,
    svgElement: `<g id="dissection_bahir_dasharam" stroke="#FFD700" stroke-width="2" stroke-linejoin="round">
  <polygon id="bahir_dasharam_0" points="500,315 540.79,374.46 459.21,374.46" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_1" points="608.74,350.33 606.79,422.41 540.79,374.46" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_2" points="675.95,442.83 632,500 606.79,422.41" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_3" points="675.95,557.17 606.79,577.59 632,500" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_4" points="608.74,649.67 540.79,625.54 606.79,577.59" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_5" points="500,685 459.21,625.54 540.79,625.54" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_6" points="391.26,649.67 393.21,577.59 459.21,625.54" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_7" points="324.05,557.17 368,500 393.21,577.59" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_8" points="324.05,442.83 393.21,422.41 368,500" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_9" points="391.26,350.33 459.21,374.46 393.21,422.41" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  6: {
    index: 6,
    nameSanskrit: "सर्वरक्षाकर चक्र (अन्तर्दशार / 10 भीतरी त्रिकोण)",
    nameEnglish: "Sarvarakshakara Chakra (10 Inner Triangles)",
    chakraTitle: "अन्तर्दशार चक्र",
    geometryType: "10 Inner Circuit Triangles",
    count: 10,
    svgElement: `<g id="dissection_antar_dasharam" stroke="#FFD700" stroke-width="2" stroke-linejoin="round">
  <polygon id="antar_dasharam_0" points="540.79,374.46 551.73,428.81 500,412" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_1" points="606.79,422.41 583.69,472.81 551.73,428.81" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_2" points="632,500 583.69,527.19 583.69,472.81" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_3" points="606.79,577.59 551.73,571.19 583.69,527.19" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_4" points="540.79,625.54 500,588 551.73,571.19" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_5" points="459.21,625.54 448.27,571.19 500,588" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_6" points="393.21,577.59 416.31,527.19 448.27,571.19" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_7" points="368,500 416.31,472.81 416.31,527.19" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_8" points="393.21,422.41 448.27,428.81 416.31,472.81" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_9" points="459.21,374.46 500,412 448.27,428.81" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  7: {
    index: 7,
    nameSanskrit: "सर्वरोगहर चक्र (अष्टार / 8 त्रिकोण)",
    nameEnglish: "Sarvarogahara Chakra (8 Inner Triangles)",
    chakraTitle: "अष्टकोण चक्र",
    geometryType: "8 Interlocking Circuit Triangles",
    count: 8,
    svgElement: `<g id="dissection_ashtaragon" stroke="#FFD700" stroke-width="2.2" stroke-linejoin="round">
  <polygon id="ashtaragon_0" points="500,412 519.13,453.81 480.87,453.81" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_1" points="562.23,437.77 546.19,480.87 519.13,453.81" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_2" points="588,500 546.19,519.13 546.19,480.87" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_3" points="562.23,562.23 519.13,546.19 546.19,519.13" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_4" points="500,588 480.87,546.19 519.13,546.19" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_5" points="437.77,562.23 453.81,519.13 480.87,546.19" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_6" points="412,500 453.81,480.87 453.81,519.13" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_7" points="437.77,437.77 480.87,453.81 453.81,480.87" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  8: {
    index: 8,
    nameSanskrit: "सर्वसिद्धिप्रद चक्र (मूल त्रिकोण / काम-कला)",
    nameEnglish: "Sarvasiddhiprada Chakra (Central Inverted Triangle)",
    chakraTitle: "काम-कला अधोमुख त्रिकोण",
    geometryType: "Downward-Pointing Primordial Triangle",
    count: 1,
    svgElement: `<g id="dissection_trikona" stroke="#FFD700" stroke-width="2.6" stroke-linejoin="round">
  <polygon id="face_central_kama_kala_trikona" points="436.53,486.99 563.47,486.99 500,560.62" fill="rgba(255,215,0,0.38)" stroke="#FFE066" stroke-width="2.6" />
  <circle cx="500" cy="500" r="5" fill="#FFE875" stroke="#FFFFFF" stroke-width="1.5" />
</g>`
  },
  9: {
    index: 9,
    nameSanskrit: "सर्वानन्दमय चक्र (बिन्दु)",
    nameEnglish: "Sarvanandamaya Chakra (Bindu Point)",
    chakraTitle: "परब्रह्म महाबिन्दु",
    geometryType: "Singularity / Central Radiant Point",
    count: 1,
    svgElement: `<g id="dissection_bindu">
  <circle cx="500" cy="500" r="32" fill="rgba(255,215,0,0.12)" stroke="#FFE066" stroke-width="1.5" stroke-dasharray="4 3" />
  <circle cx="500" cy="500" r="18" fill="none" stroke="#FFD700" stroke-width="1.8" />
  <circle cx="500" cy="500" r="8" fill="url(#binduRadiance)" stroke="#FFFFFF" stroke-width="2" />
</g>`
  }
};
