// Autogenerated pure vector geometric dissection models for Sri Yantra
// Perfectly symmetric, topologically verified, canonical 9-Avarana vectors
// Scale: 1000x1000 viewBox, center (500, 500)

export interface AvaranaDissectionData {
  index: number;
  nameSanskrit: string;
  nameEnglish: string;
  chakraTitle: string;
  geometryType: string;
  count: number;
  svgElement: string;
}

export const SRI_YANTRA_VECTOR_DISSECTIONS: Record<number, AvaranaDissectionData> = {
  1: {
    index: 1,
    nameSanskrit: "त्रैलोक्यमोहन चक्र (भूपुर प्राकार / 3 रेखाएं व 4 द्वार)",
    nameEnglish: "Trailokyamohana Chakra (Bhupura Earth Rampart & 4 Gates)",
    chakraTitle: "भूपुर प्राकार (चतुरस्र)",
    geometryType: "3 Stepped Concentric Squares with 4 Cardinal Portals",
    count: 4,
    svgElement: `<g id="dissection_bhupura">
  <path d="M 60 60 L 420.8 60 L 420.8 24.8 L 579.2 24.8 L 579.2 60 L 940 60 L 940 420.8 L 975.2 420.8 L 975.2 579.2 L 940 579.2 L 940 940 L 579.2 940 L 579.2 975.2 L 420.8 975.2 L 420.8 940 L 60 940 L 60 579.2 L 24.8 579.2 L 24.8 420.8 L 60 420.8 Z M 79.8 79.8 L 440.6 79.8 L 440.6 44.6 L 559.4 44.6 L 559.4 79.8 L 920.2 79.8 L 920.2 440.6 L 955.4 440.6 L 955.4 559.4 L 920.2 559.4 L 920.2 920.2 L 559.4 920.2 L 559.4 955.4 L 440.6 955.4 L 440.6 920.2 L 79.8 920.2 L 79.8 559.4 L 44.6 559.4 L 44.6 440.6 L 79.8 440.6 Z M 99.6 99.6 L 460.4 99.6 L 460.4 64.4 L 539.6 64.4 L 539.6 99.6 L 900.4 99.6 L 900.4 460.4 L 935.6 460.4 L 935.6 539.6 L 900.4 539.6 L 900.4 900.4 L 539.6 900.4 L 539.6 935.6 L 460.4 935.6 L 460.4 900.4 L 99.6 900.4 L 99.6 539.6 L 64.4 539.6 L 64.4 460.4 L 99.6 460.4 Z" fill="none" stroke="#FFD700" stroke-width="2.6" stroke-linejoin="round" />
</g>`
  },
  2: {
    index: 2,
    nameSanskrit: "सर्वाशापरिपूरक चक्र (षोडशदल पद्म / 16 कमल पंखुड़ियाँ)",
    nameEnglish: "Sarvashaparipuraka Chakra (16-Petal Lotus)",
    chakraTitle: "षोडशदल पद्म चक्र",
    geometryType: "16 Sacred Lotus Petals with Outer Ring",
    count: 16,
    svgElement: `<g id="dissection_shodashadala">
  <circle cx="500" cy="500" r="356" fill="none" stroke="#FFD700" stroke-width="1.8" stroke-dasharray="3 3" opacity="0.6" />
  <path d="M 444.2 219.5 Q 463.09 165.63, 500 144 Q 536.91 165.63, 555.8 219.5 M 555.8 219.5 Q 593.85 176.96, 636.24 171.1 Q 662.06 205.21, 658.89 262.2 M 658.89 262.2 Q 710.33 237.46, 751.73 248.27 Q 762.54 289.67, 737.8 341.11 M 737.8 341.11 Q 794.79 337.94, 828.9 363.76 Q 823.04 406.15, 780.5 444.2 M 780.5 444.2 Q 834.37 463.09, 856 500 Q 834.37 536.91, 780.5 555.8 M 780.5 555.8 Q 823.04 593.85, 828.9 636.24 Q 794.79 662.06, 737.8 658.89 M 737.8 658.89 Q 762.54 710.33, 751.73 751.73 Q 710.33 762.54, 658.89 737.8 M 658.89 737.8 Q 662.06 794.79, 636.24 828.9 Q 593.85 823.04, 555.8 780.5 M 555.8 780.5 Q 536.91 834.37, 500 856 Q 463.09 834.37, 444.2 780.5 M 444.2 780.5 Q 406.15 823.04, 363.76 828.9 Q 337.94 794.79, 341.11 737.8 M 341.11 737.8 Q 289.67 762.54, 248.27 751.73 Q 237.46 710.33, 262.2 658.89 M 262.2 658.89 Q 205.21 662.06, 171.1 636.24 Q 176.96 593.85, 219.5 555.8 M 219.5 555.8 Q 165.63 536.91, 144 500 Q 165.63 463.09, 219.5 444.2 M 219.5 444.2 Q 176.96 406.15, 171.1 363.76 Q 205.21 337.94, 262.2 341.11 M 262.2 341.11 Q 237.46 289.67, 248.27 248.27 Q 289.67 237.46, 341.11 262.2 M 341.11 262.2 Q 337.94 205.21, 363.76 171.1 Q 406.15 176.96, 444.2 219.5 " fill="rgba(212,175,55,0.18)" stroke="#FFD700" stroke-width="2.2" stroke-linejoin="round" />
  <circle cx="500" cy="500" r="286" fill="none" stroke="#FFD700" stroke-width="1.8" />
</g>`
  },
  3: {
    index: 3,
    nameSanskrit: "सर्वसंक्षोभण चक्र (अष्टदल पद्म / 8 कमल पंखुड़ियाँ)",
    nameEnglish: "Sarvasankshobhana Chakra (8-Petal Lotus)",
    chakraTitle: "अष्टदल पद्म चक्र",
    geometryType: "8 Sacred Lotus Petals with Concentric Boundaries",
    count: 8,
    svgElement: `<g id="dissection_ashtadala">
  <circle cx="500" cy="500" r="286" fill="none" stroke="#FFD700" stroke-width="1.8" />
  <path d="M 415.81 296.75 Q 441.64 238.92, 500 214 Q 558.36 238.92, 584.19 296.75 M 584.19 296.75 Q 643.34 274.13, 702.23 297.77 Q 725.87 356.66, 703.25 415.81 M 703.25 415.81 Q 761.08 441.64, 786 500 Q 761.08 558.36, 703.25 584.19 M 703.25 584.19 Q 725.87 643.34, 702.23 702.23 Q 643.34 725.87, 584.19 703.25 M 584.19 703.25 Q 558.36 761.08, 500 786 Q 441.64 761.08, 415.81 703.25 M 415.81 703.25 Q 356.66 725.87, 297.77 702.23 Q 274.13 643.34, 296.75 584.19 M 296.75 584.19 Q 238.92 558.36, 214 500 Q 238.92 441.64, 296.75 415.81 M 296.75 415.81 Q 274.13 356.66, 297.77 297.77 Q 356.66 274.13, 415.81 296.75 " fill="rgba(217,119,6,0.22)" stroke="#FFD700" stroke-width="2.4" stroke-linejoin="round" />
  <circle cx="500" cy="500" r="220" fill="none" stroke="#FFD700" stroke-width="1.8" />
</g>`
  },
  4: {
    index: 4,
    nameSanskrit: "सर्वसौभाग्यदायक चक्र (चतुर्दशार / 14 त्रिकोण)",
    nameEnglish: "Sarvasaubhagyadayaka Chakra (14 Triangles)",
    chakraTitle: "चतुर्दशार चक्र",
    geometryType: "14 Outer Perimeter Triangles",
    count: 14,
    svgElement: `<g id="dissection_chaturdasharam" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round">
  <circle cx="500" cy="500" r="220" fill="none" stroke="#FFD700" stroke-width="1.2" opacity="0.5" stroke-dasharray="4 2" />
  <polygon id="chaturdasharam_0" points="500,282 535.6,344.01 464.4,344.01" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_1" points="594.59,303.59 599.76,374.91 535.6,344.01" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_2" points="670.44,364.08 644.16,430.58 599.76,374.91" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_3" points="712.53,451.49 660,500 644.16,430.58" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_4" points="712.53,548.51 644.16,569.42 660,500" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_5" points="670.44,635.92 599.76,625.09 644.16,569.42" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_6" points="594.59,696.41 535.6,655.99 599.76,625.09" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_7" points="500,718 464.4,655.99 535.6,655.99" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_8" points="405.41,696.41 400.24,625.09 464.4,655.99" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_9" points="329.56,635.92 355.84,569.42 400.24,625.09" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_10" points="287.47,548.51 340,500 355.84,569.42" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_11" points="287.47,451.49 355.84,430.58 340,500" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_12" points="329.56,364.08 400.24,374.91 355.84,430.58" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="chaturdasharam_13" points="405.41,303.59 464.4,344.01 400.24,374.91" fill="rgba(245,158,11,0.26)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  5: {
    index: 5,
    nameSanskrit: "सर्वार्थसाधक चक्र (बहिर्दशार / 10 बाहरी त्रिकोण)",
    nameEnglish: "Sarvarthasadhaka Chakra (10 Outer Triangles)",
    chakraTitle: "बहिर्दशार चक्र",
    geometryType: "10 Outer Circuit Triangles",
    count: 10,
    svgElement: `<g id="dissection_bahir_dasharam" stroke="#FFD700" stroke-width="2" stroke-linejoin="round">
  <polygon id="bahir_dasharam_0" points="500,340 535.85,389.68 464.15,389.68" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_1" points="594.05,370.56 593.85,431.82 535.85,389.68" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_2" points="652.17,450.56 616,500 593.85,431.82" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_3" points="652.17,549.44 593.85,568.18 616,500" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_4" points="594.05,629.44 535.85,610.32 593.85,568.18" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_5" points="500,660 464.15,610.32 535.85,610.32" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_6" points="405.95,629.44 406.15,568.18 464.15,610.32" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_7" points="347.83,549.44 384,500 406.15,568.18" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_8" points="347.83,450.56 406.15,431.82 384,500" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="bahir_dasharam_9" points="405.95,370.56 464.15,389.68 406.15,431.82" fill="rgba(217,119,6,0.30)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  6: {
    index: 6,
    nameSanskrit: "सर्वरक्षाकर चक्र (अन्तर्दशार / 10 भीतरी त्रिकोण)",
    nameEnglish: "Sarvarakshakara Chakra (10 Inner Triangles)",
    chakraTitle: "अन्तर्दशार चक्र",
    geometryType: "10 Inner Circuit Triangles",
    count: 10,
    svgElement: `<g id="dissection_antar_dasharam" stroke="#FFD700" stroke-width="2" stroke-linejoin="round">
  <polygon id="antar_dasharam_0" points="535.85,389.68 545.85,436.9 500,422" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_1" points="593.85,431.82 574.18,475.9 545.85,436.9" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_2" points="616,500 574.18,524.1 574.18,475.9" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_3" points="593.85,568.18 545.85,563.1 574.18,524.1" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_4" points="535.85,610.32 500,578 545.85,563.1" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_5" points="464.15,610.32 454.15,563.1 500,578" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_6" points="406.15,568.18 425.82,524.1 454.15,563.1" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_7" points="384,500 425.82,475.9 425.82,524.1" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_8" points="406.15,431.82 454.15,436.9 425.82,475.9" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="antar_dasharam_9" points="464.15,389.68 500,422 454.15,436.9" fill="rgba(245,158,11,0.32)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  7: {
    index: 7,
    nameSanskrit: "सर्वरोगहर चक्र (अष्टार / 8 त्रिकोण)",
    nameEnglish: "Sarvarogahara Chakra (8 Inner Triangles)",
    chakraTitle: "अष्टकोण चक्र",
    geometryType: "8 Interlocking Circuit Triangles",
    count: 8,
    svgElement: `<g id="dissection_ashtaragon" stroke="#FFD700" stroke-width="2.2" stroke-linejoin="round">
  <polygon id="ashtaragon_0" points="500,422 516.84,459.35 483.16,459.35" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_1" points="555.15,444.85 540.65,483.16 516.84,459.35" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_2" points="578,500 540.65,516.84 540.65,483.16" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_3" points="555.15,555.15 516.84,540.65 540.65,516.84" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_4" points="500,578 483.16,540.65 516.84,540.65" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_5" points="444.85,555.15 459.35,516.84 483.16,540.65" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_6" points="422,500 459.35,483.16 459.35,516.84" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    <polygon id="ashtaragon_7" points="444.85,444.85 483.16,459.35 459.35,483.16" fill="rgba(217,119,6,0.35)" stroke="#FFD700" stroke-width="1.8" stroke-linejoin="round" />
    
</g>`
  },
  8: {
    index: 8,
    nameSanskrit: "सर्वसिद्धिप्रद चक्र (मूल त्रिकोण / काम-कला)",
    nameEnglish: "Sarvasiddhiprada Chakra (Central Inverted Triangle)",
    chakraTitle: "काम-कला अधोमुख त्रिकोण",
    geometryType: "Downward-Pointing Primordial Triangle",
    count: 1,
    svgElement: `<g id="dissection_trikona" stroke="#FFD700" stroke-width="2.6" stroke-linejoin="round">
  <polygon id="face_central_kama_kala_trikona" points="423.84,484.39 576.16,484.39 500,572.74" fill="rgba(255,215,0,0.38)" stroke="#FFE066" stroke-width="2.6" />
  <circle cx="500" cy="500" r="5" fill="#FFE875" stroke="#FFFFFF" stroke-width="1.5" />
</g>`
  },
  9: {
    index: 9,
    nameSanskrit: "सर्वानन्दमय चक्र (बिन्दु)",
    nameEnglish: "Sarvanandamaya Chakra (Bindu Point)",
    chakraTitle: "परब्रह्म महाबिन्दु",
    geometryType: "Singularity / Central Radiant Point",
    count: 1,
    svgElement: `<g id="dissection_bindu">
  <circle cx="500" cy="500" r="36" fill="rgba(255,215,0,0.12)" stroke="#FFE066" stroke-width="1.5" stroke-dasharray="4 3" />
  <circle cx="500" cy="500" r="20" fill="none" stroke="#FFD700" stroke-width="1.8" />
  <circle cx="500" cy="500" r="10" fill="url(#binduRadiance)" stroke="#FFFFFF" stroke-width="2" />
</g>`
  }
};
