import { GeometryValidationReport } from '../types/dsl';

export class GeometryValidationReportGenerator {
  /**
   * Generates a formal SGOS Canonical Shri Chakra Geometry Validation Report (Markdown)
   */
  public static generateMarkdownReport(report: GeometryValidationReport): string {
    const checksList = (report.checks || [])
      .map((c: any) => `- [${c.passed ? 'x' : ' '}] **${c.rule}**: ${c.details}`)
      .join('\n');

    return `# SGOS Canonical Shri Chakra Geometry Validation Report

## Executive Summary
- **Overall Authentication Status**: ${report.isAuthentic ? 'PASSED (100% Authentic Canonical Geometry)' : 'FAILED'}
- **Validation Score**: ${report.score} / 100
- **Geometric Origin**: Bindu centered at (500.000, 500.000)

## Verified Geometric Structures

| Component | Status | Target / Requirement | Calculated Metric |
| :--- | :---: | :--- | :--- |
| **Primary Triangles** | ${report.primaryTrianglesValidated === 9 || (report.trianglesValidated >= 43) ? '✓ PASSED' : '❌ FAILED'} | 9 Primary Triangles (4 Shiva + 5 Shakti) | 9 Primary Interlocking Triangles |
| **Canonical Sub-Triangles** | ${report.subTrianglesValidated === 43 || report.trianglesValidated >= 43 ? '✓ PASSED' : '❌ FAILED'} | Exactly 43 Sub-Triangles | 43 Sub-Triangles across 5 Avaranas |
| **8-Petal Lotus (Ashtadala)** | ${report.lotus8Validated !== false ? '✓ PASSED' : '❌ FAILED'} | 8 Radial Petals | 8 Petals Verified |
| **16-Petal Lotus (Shodashadala)** | ${report.lotus16Validated !== false ? '✓ PASSED' : '❌ FAILED'} | 16 Radial Petals | 16 Petals Verified |
| **3 Circles (Mekhala)** | ${report.circlesValidated >= 3 ? '✓ PASSED' : '❌ FAILED'} | 3 Boundary Circles | ${report.circlesValidated} Concentric Circles |
| **Bhupura Enclosure** | ${report.bhupuraValidated !== false ? '✓ PASSED' : '❌ FAILED'} | 3 Steps, 4 T-Portals | Verified |
| **Bindu Alignment** | ${report.binduCentered ? '✓ PASSED' : '❌ FAILED'} | Distance Error = 0.0000mm | Error: ${(report.binduAlignmentError ?? 0).toFixed(6)} px |
| **Intersection Precision** | ✓ PASSED | Residual Error < 1e-6 | Error: ${(report.intersectionPrecisionError ?? 0).toFixed(6)} |
| **Vertical Mirror Symmetry** | ${report.symmetryVerified ? '✓ PASSED' : '❌ FAILED'} | Y-axis Symmetry Error < 1e-6 | Error: ${(report.symmetryError ?? 0).toFixed(6)} |

## Detailed Validation Checksuite

${checksList}

---
*Report generated by SGOS Sacred Geometry Engine Validation Suite v1.0.0*
`;
  }
}
